/*
  LHS – Candidate module database
  02: Tables, keys, constraints and indexes. Safe to re-run: existing objects are left untouched.
  Mirrors the SPA data model (Candidates/js/domain.js, store.js). Requirement refs are to ICT_Labour_Hire_System_Requirements.md.

  Conventions
    - Ids are UNIQUEIDENTIFIER to match the UUIDs generated by the web app.
    - Timestamps are UTC DATETIME2(3); calendar dates (expiry, availability) are DATE.
    - Optional text is NULL, never '' (the API layer maps empty strings to NULL).
    - Personal information is soft-erased via candidates.usp_EraseCandidate (Privacy Act), never hard-deleted ad hoc.
*/
USE [$(DatabaseName)];
GO
SET NOCOUNT ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO

/* ---------- ABN checksum (req 2.10). Created before the tables because a CHECK constraint uses it. ---------- */
IF OBJECT_ID(N'candidates.fn_IsValidAbn', N'FN') IS NULL
EXEC (N'
CREATE FUNCTION candidates.fn_IsValidAbn (@Abn CHAR(11))
RETURNS BIT
WITH SCHEMABINDING
AS
BEGIN
    IF @Abn IS NULL OR LEN(@Abn) <> 11 OR @Abn LIKE ''%[^0-9]%'' RETURN 0;
    DECLARE @Sum INT =
          (CAST(SUBSTRING(@Abn, 1, 1) AS INT) - 1) * 10
        + CAST(SUBSTRING(@Abn, 2, 1) AS INT) * 1
        + CAST(SUBSTRING(@Abn, 3, 1) AS INT) * 3
        + CAST(SUBSTRING(@Abn, 4, 1) AS INT) * 5
        + CAST(SUBSTRING(@Abn, 5, 1) AS INT) * 7
        + CAST(SUBSTRING(@Abn, 6, 1) AS INT) * 9
        + CAST(SUBSTRING(@Abn, 7, 1) AS INT) * 11
        + CAST(SUBSTRING(@Abn, 8, 1) AS INT) * 13
        + CAST(SUBSTRING(@Abn, 9, 1) AS INT) * 15
        + CAST(SUBSTRING(@Abn, 10, 1) AS INT) * 17
        + CAST(SUBSTRING(@Abn, 11, 1) AS INT) * 19;
    RETURN CASE WHEN @Sum % 89 = 0 THEN 1 ELSE 0 END;
END');
GO

/* ======================= Reference (lookup) tables ======================= */

-- Candidate status workflow states (req 3.1.5).
IF OBJECT_ID(N'candidates.CandidateStatus', N'U') IS NULL
CREATE TABLE candidates.CandidateStatus (
    StatusCode      NVARCHAR(20)  NOT NULL CONSTRAINT PK_CandidateStatus PRIMARY KEY,
    SortOrder       TINYINT       NOT NULL,
    IsPipeline      BIT           NOT NULL,   -- on the main Prospect → Bench path
    CandidateLabel  NVARCHAR(60)  NOT NULL    -- wording shown in the candidate portal (never "Do Not Use")
);
GO

-- Allowed status moves. Compliance gates are checked separately in candidates.fn_StatusGateIssues.
IF OBJECT_ID(N'candidates.StatusTransition', N'U') IS NULL
CREATE TABLE candidates.StatusTransition (
    FromStatus      NVARCHAR(20)  NOT NULL CONSTRAINT FK_StatusTransition_From REFERENCES candidates.CandidateStatus (StatusCode),
    ToStatus        NVARCHAR(20)  NOT NULL CONSTRAINT FK_StatusTransition_To   REFERENCES candidates.CandidateStatus (StatusCode),
    RequiresReason  BIT           NOT NULL CONSTRAINT DF_StatusTransition_RequiresReason DEFAULT (0),
    CONSTRAINT PK_StatusTransition PRIMARY KEY (FromStatus, ToStatus),
    CONSTRAINT CK_StatusTransition_NotSelf CHECK (FromStatus <> ToStatus)
);
GO

-- How candidates are found (req 3.1.1 sourcing attribution).
IF OBJECT_ID(N'candidates.SourceChannel', N'U') IS NULL
CREATE TABLE candidates.SourceChannel (
    SourceChannelCode NVARCHAR(30) NOT NULL CONSTRAINT PK_SourceChannel PRIMARY KEY
);
GO

-- Compliance document types (req 3.1.3).
IF OBJECT_ID(N'candidates.DocumentType', N'U') IS NULL
CREATE TABLE candidates.DocumentType (
    DocumentTypeCode       NVARCHAR(40) NOT NULL CONSTRAINT PK_DocumentType PRIMARY KEY,
    IsOnboardingRequired   BIT          NOT NULL CONSTRAINT DF_DocumentType_Onboarding DEFAULT (0), -- needed before Active
    CandidateCanUpload     BIT          NOT NULL CONSTRAINT DF_DocumentType_Upload DEFAULT (1),     -- allowed via the portal
    SortOrder              TINYINT      NOT NULL
);
GO

-- Mandatory / optional inductions (req 3.1.3).
IF OBJECT_ID(N'candidates.InductionType', N'U') IS NULL
CREATE TABLE candidates.InductionType (
    InductionTypeCode NVARCHAR(30) NOT NULL CONSTRAINT PK_InductionType PRIMARY KEY,
    IsMandatory       BIT          NOT NULL,
    SortOrder         TINYINT      NOT NULL
);
GO

/* ======================= Candidate ======================= */

IF OBJECT_ID(N'candidates.Candidate', N'U') IS NULL
CREATE TABLE candidates.Candidate (
    CandidateId              UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_Candidate_Id DEFAULT (NEWSEQUENTIALID()),
    StatusCode               NVARCHAR(20)     NOT NULL CONSTRAINT DF_Candidate_Status DEFAULT (N'Prospect')
                                              CONSTRAINT FK_Candidate_Status REFERENCES candidates.CandidateStatus (StatusCode),

    -- Personal & contact (req 3.1.1)
    FirstName                NVARCHAR(100)    NULL,
    LastName                 NVARCHAR(100)    NULL,
    Email                    NVARCHAR(254)    NULL,
    Phone                    NVARCHAR(30)     NULL,
    Location                 NVARCHAR(120)    NULL,
    CurrentEmployer          NVARCHAR(150)    NULL,
    CurrentTitle             NVARCHAR(150)    NULL,
    Abn                      CHAR(11)         NULL,
    AvailabilityDate         DATE             NULL,
    SalaryBasis              NVARCHAR(20)     NOT NULL CONSTRAINT DF_Candidate_SalaryBasis DEFAULT (N'Daily rate'),
    SalaryAmount             DECIMAL(12, 2)   NULL,

    -- Security clearance (req 3.1.1 / 3.1.2)
    ClearanceLevel           NVARCHAR(10)     NOT NULL CONSTRAINT DF_Candidate_ClearanceLevel DEFAULT (N'None'),
    ClearanceExpiry          DATE             NULL,
    ClearanceIssuingAgency   NVARCHAR(100)    NULL,
    ClearanceVerification    NVARCHAR(12)     NOT NULL CONSTRAINT DF_Candidate_ClearanceVerification DEFAULT (N'Unverified'),

    -- Right to work (req 3.1.2)
    WorkRights               NVARCHAR(30)     NULL,
    VisaType                 NVARCHAR(60)     NULL,
    VisaExpiry               DATE             NULL,
    VisaRestrictions         NVARCHAR(200)    NULL,

    -- Sourcing & LinkedIn (req 3.1.1)
    SourceChannelCode        NVARCHAR(30)     NULL CONSTRAINT FK_Candidate_SourceChannel REFERENCES candidates.SourceChannel (SourceChannelCode),
    SourceDetail             NVARCHAR(200)    NULL,
    LinkedInUrl              NVARCHAR(300)    NULL,
    LinkedInOutreachStatus   NVARCHAR(20)     NOT NULL CONSTRAINT DF_Candidate_Outreach DEFAULT (N'Not contacted'),

    -- Privacy Act consent (req 3.1.1 / 2.10)
    ConsentGiven             BIT              NOT NULL CONSTRAINT DF_Candidate_ConsentGiven DEFAULT (0),
    ConsentDate              DATE             NULL,
    ConsentMethod            NVARCHAR(30)     NULL,
    CollectionNoticeProvided BIT              NOT NULL CONSTRAINT DF_Candidate_CollectionNotice DEFAULT (0),

    Notes                    NVARCHAR(MAX)    NULL,   -- internal only; never exposed to the candidate portal

    -- Privacy erasure tombstone & merge trail (req 3.10.2 / 3.1.1)
    IsErased                 BIT              NOT NULL CONSTRAINT DF_Candidate_IsErased DEFAULT (0),
    ErasedAt                 DATETIME2(3)     NULL,
    ErasureReason            NVARCHAR(500)    NULL,

    CreatedAt                DATETIME2(3)     NOT NULL CONSTRAINT DF_Candidate_CreatedAt DEFAULT (SYSUTCDATETIME()),
    UpdatedAt                DATETIME2(3)     NOT NULL CONSTRAINT DF_Candidate_UpdatedAt DEFAULT (SYSUTCDATETIME()),  -- "last activity" for 7-year retention
    RowVer                   ROWVERSION       NOT NULL,  -- optimistic concurrency for the API

    -- Normalised match keys for duplicate detection (same rules as domain.js).
    EmailKey    AS (LOWER(LTRIM(RTRIM(Email)))) PERSISTED,
    PhoneKey    AS (CASE WHEN LEN(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(Phone, N' ', N''), N'-', N''), N'(', N''), N')', N''), N'+', N'')) >= 9
                         THEN RIGHT(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(Phone, N' ', N''), N'-', N''), N'(', N''), N')', N''), N'+', N''), 9) END) PERSISTED,
    LinkedInKey AS (CAST(LOWER(TRIM(N'/ ' FROM REPLACE(REPLACE(REPLACE(LinkedInUrl, N'https://', N''), N'http://', N''), N'www.', N''))) AS NVARCHAR(300))) PERSISTED,

    CONSTRAINT PK_Candidate PRIMARY KEY CLUSTERED (CandidateId),
    CONSTRAINT CK_Candidate_Name            CHECK (IsErased = 1 OR (FirstName IS NOT NULL AND LastName IS NOT NULL)),
    CONSTRAINT CK_Candidate_Contact         CHECK (IsErased = 1 OR Email IS NOT NULL OR Phone IS NOT NULL OR LinkedInUrl IS NOT NULL),
    CONSTRAINT CK_Candidate_Email           CHECK (Email IS NULL OR Email LIKE N'_%@_%._%'),
    CONSTRAINT CK_Candidate_Abn             CHECK (Abn IS NULL OR candidates.fn_IsValidAbn(Abn) = 1),
    CONSTRAINT CK_Candidate_SalaryBasis     CHECK (SalaryBasis IN (N'Daily rate', N'Hourly rate', N'Annual salary')),
    CONSTRAINT CK_Candidate_SalaryAmount    CHECK (SalaryAmount IS NULL OR SalaryAmount >= 0),
    CONSTRAINT CK_Candidate_ClearanceLevel  CHECK (ClearanceLevel IN (N'None', N'Baseline', N'NV1', N'NV2', N'PV')),
    CONSTRAINT CK_Candidate_ClearanceVerif  CHECK (ClearanceVerification IN (N'Unverified', N'Pending', N'Verified', N'Failed')),
    CONSTRAINT CK_Candidate_ClearanceExpiry CHECK (ClearanceLevel = N'None' OR ClearanceExpiry IS NOT NULL OR IsErased = 1),
    CONSTRAINT CK_Candidate_WorkRights      CHECK (WorkRights IS NULL OR WorkRights IN (N'Australian citizen', N'Permanent resident', N'NZ citizen', N'Visa holder')),
    CONSTRAINT CK_Candidate_VisaExpiry      CHECK (WorkRights IS NULL OR WorkRights <> N'Visa holder' OR VisaExpiry IS NOT NULL),
    CONSTRAINT CK_Candidate_Outreach        CHECK (LinkedInOutreachStatus IN (N'Not contacted', N'InMail sent', N'Responded', N'Interested', N'Not interested')),
    CONSTRAINT CK_Candidate_LinkedInUrl     CHECK (LinkedInUrl IS NULL OR LinkedInUrl LIKE N'http%://%linkedin.com/%'),
    CONSTRAINT CK_Candidate_ConsentMethod   CHECK (ConsentMethod IS NULL OR ConsentMethod IN (N'Email', N'Written form', N'Verbal (recorded)', N'Candidate portal')),
    CONSTRAINT CK_Candidate_Consent         CHECK (ConsentGiven = 0 OR (ConsentDate IS NOT NULL AND ConsentMethod IS NOT NULL)),
    CONSTRAINT CK_Candidate_Erased          CHECK (IsErased = 0 OR (ErasedAt IS NOT NULL AND FirstName IS NULL AND LastName IS NULL AND Email IS NULL AND Phone IS NULL))
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_Candidate_Status' AND object_id = OBJECT_ID(N'candidates.Candidate'))
    CREATE INDEX IX_Candidate_Status ON candidates.Candidate (StatusCode) INCLUDE (FirstName, LastName, ClearanceLevel, AvailabilityDate) WHERE IsErased = 0;
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_Candidate_Name' AND object_id = OBJECT_ID(N'candidates.Candidate'))
    CREATE INDEX IX_Candidate_Name ON candidates.Candidate (LastName, FirstName) WHERE IsErased = 0;
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_Candidate_EmailKey' AND object_id = OBJECT_ID(N'candidates.Candidate'))
    CREATE INDEX IX_Candidate_EmailKey ON candidates.Candidate (EmailKey) WHERE Email IS NOT NULL;  -- filters can't use computed columns
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_Candidate_PhoneKey' AND object_id = OBJECT_ID(N'candidates.Candidate'))
    CREATE INDEX IX_Candidate_PhoneKey ON candidates.Candidate (PhoneKey) WHERE Phone IS NOT NULL;
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_Candidate_LinkedInKey' AND object_id = OBJECT_ID(N'candidates.Candidate'))
    CREATE INDEX IX_Candidate_LinkedInKey ON candidates.Candidate (LinkedInKey) WHERE LinkedInUrl IS NOT NULL;
GO

/* ======================= Profile detail ======================= */

IF OBJECT_ID(N'candidates.CandidateSkill', N'U') IS NULL
CREATE TABLE candidates.CandidateSkill (
    CandidateSkillId  UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_CandidateSkill_Id DEFAULT (NEWSEQUENTIALID()) CONSTRAINT PK_CandidateSkill PRIMARY KEY,
    CandidateId       UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_CandidateSkill_Candidate REFERENCES candidates.Candidate (CandidateId) ON DELETE CASCADE,
    SkillName         NVARCHAR(100)    NOT NULL,
    YearsExperience   DECIMAL(4, 1)    NULL CONSTRAINT CK_CandidateSkill_Years CHECK (YearsExperience IS NULL OR YearsExperience BETWEEN 0 AND 60),
    CONSTRAINT UQ_CandidateSkill UNIQUE (CandidateId, SkillName)
);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_CandidateSkill_SkillName' AND object_id = OBJECT_ID(N'candidates.CandidateSkill'))
    CREATE INDEX IX_CandidateSkill_SkillName ON candidates.CandidateSkill (SkillName) INCLUDE (CandidateId, YearsExperience);
GO

IF OBJECT_ID(N'candidates.CandidateCertification', N'U') IS NULL
CREATE TABLE candidates.CandidateCertification (
    CertificationId   UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_CandidateCertification_Id DEFAULT (NEWSEQUENTIALID()) CONSTRAINT PK_CandidateCertification PRIMARY KEY,
    CandidateId       UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_CandidateCertification_Candidate REFERENCES candidates.Candidate (CandidateId) ON DELETE CASCADE,
    CertificationName NVARCHAR(150)    NOT NULL,
    Issuer            NVARCHAR(150)    NULL,
    ExpiryDate        DATE             NULL
);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_CandidateCertification_Candidate' AND object_id = OBJECT_ID(N'candidates.CandidateCertification'))
    CREATE INDEX IX_CandidateCertification_Candidate ON candidates.CandidateCertification (CandidateId);
GO

-- LinkedIn / outreach contact history (req 3.1.1, 3.4.3).
IF OBJECT_ID(N'candidates.OutreachLog', N'U') IS NULL
CREATE TABLE candidates.OutreachLog (
    OutreachId        UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_OutreachLog_Id DEFAULT (NEWSEQUENTIALID()) CONSTRAINT PK_OutreachLog PRIMARY KEY,
    CandidateId       UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_OutreachLog_Candidate REFERENCES candidates.Candidate (CandidateId) ON DELETE CASCADE,
    OutreachDate      DATE             NOT NULL,
    Channel           NVARCHAR(30)     NOT NULL CONSTRAINT CK_OutreachLog_Channel CHECK (Channel IN (N'InMail', N'Connection request', N'Email', N'Phone call')),
    OutreachStatus    NVARCHAR(20)     NOT NULL CONSTRAINT CK_OutreachLog_Status CHECK (OutreachStatus IN (N'Not contacted', N'InMail sent', N'Responded', N'Interested', N'Not interested')),
    Note              NVARCHAR(1000)   NULL
);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_OutreachLog_Candidate' AND object_id = OBJECT_ID(N'candidates.OutreachLog'))
    CREATE INDEX IX_OutreachLog_Candidate ON candidates.OutreachLog (CandidateId, OutreachDate);
GO

IF OBJECT_ID(N'candidates.StatusHistory', N'U') IS NULL
CREATE TABLE candidates.StatusHistory (
    StatusHistoryId   UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_StatusHistory_Id DEFAULT (NEWSEQUENTIALID()) CONSTRAINT PK_StatusHistory PRIMARY KEY,
    CandidateId       UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_StatusHistory_Candidate REFERENCES candidates.Candidate (CandidateId) ON DELETE CASCADE,
    FromStatus        NVARCHAR(20)     NULL CONSTRAINT FK_StatusHistory_From REFERENCES candidates.CandidateStatus (StatusCode),
    ToStatus          NVARCHAR(20)     NOT NULL CONSTRAINT FK_StatusHistory_To REFERENCES candidates.CandidateStatus (StatusCode),
    ChangedAt         DATETIME2(3)     NOT NULL CONSTRAINT DF_StatusHistory_ChangedAt DEFAULT (SYSUTCDATETIME()),
    ChangedBy         NVARCHAR(150)    NOT NULL,
    Reason            NVARCHAR(1000)   NULL
);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_StatusHistory_Candidate' AND object_id = OBJECT_ID(N'candidates.StatusHistory'))
    CREATE INDEX IX_StatusHistory_Candidate ON candidates.StatusHistory (CandidateId, ChangedAt);
GO

/* ======================= Screening (req 3.1.2) ======================= */

IF OBJECT_ID(N'candidates.Questionnaire', N'U') IS NULL
CREATE TABLE candidates.Questionnaire (
    QuestionnaireId   UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_Questionnaire_Id DEFAULT (NEWSEQUENTIALID()) CONSTRAINT PK_Questionnaire PRIMARY KEY,
    RoleType          NVARCHAR(100)    NOT NULL CONSTRAINT UQ_Questionnaire_RoleType UNIQUE,
    IsActive          BIT              NOT NULL CONSTRAINT DF_Questionnaire_IsActive DEFAULT (1),   -- deactivate rather than delete once used
    CreatedAt         DATETIME2(3)     NOT NULL CONSTRAINT DF_Questionnaire_CreatedAt DEFAULT (SYSUTCDATETIME()),
    UpdatedAt         DATETIME2(3)     NOT NULL CONSTRAINT DF_Questionnaire_UpdatedAt DEFAULT (SYSUTCDATETIME())
);
GO

IF OBJECT_ID(N'candidates.QuestionnaireQuestion', N'U') IS NULL
CREATE TABLE candidates.QuestionnaireQuestion (
    QuestionId        UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_QuestionnaireQuestion_Id DEFAULT (NEWSEQUENTIALID()) CONSTRAINT PK_QuestionnaireQuestion PRIMARY KEY,
    QuestionnaireId   UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_QuestionnaireQuestion_Questionnaire REFERENCES candidates.Questionnaire (QuestionnaireId) ON DELETE CASCADE,
    Sequence          SMALLINT         NOT NULL,
    QuestionText      NVARCHAR(500)    NOT NULL,
    CONSTRAINT UQ_QuestionnaireQuestion_Seq UNIQUE (QuestionnaireId, Sequence)
);
GO

-- Required skills with weight 1 (nice to have) to 3 (essential), used for skills scoring.
IF OBJECT_ID(N'candidates.QuestionnaireSkill', N'U') IS NULL
CREATE TABLE candidates.QuestionnaireSkill (
    QuestionnaireSkillId UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_QuestionnaireSkill_Id DEFAULT (NEWSEQUENTIALID()) CONSTRAINT PK_QuestionnaireSkill PRIMARY KEY,
    QuestionnaireId      UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_QuestionnaireSkill_Questionnaire REFERENCES candidates.Questionnaire (QuestionnaireId) ON DELETE CASCADE,
    SkillName            NVARCHAR(100)    NOT NULL,
    Weight               TINYINT          NOT NULL CONSTRAINT CK_QuestionnaireSkill_Weight CHECK (Weight BETWEEN 1 AND 3),
    CONSTRAINT UQ_QuestionnaireSkill UNIQUE (QuestionnaireId, SkillName)
);
GO

-- A screening keeps its own copy of questions and skills so later questionnaire edits don't rewrite history.
IF OBJECT_ID(N'candidates.Screening', N'U') IS NULL
CREATE TABLE candidates.Screening (
    ScreeningId       UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_Screening_Id DEFAULT (NEWSEQUENTIALID()) CONSTRAINT PK_Screening PRIMARY KEY,
    CandidateId       UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_Screening_Candidate REFERENCES candidates.Candidate (CandidateId) ON DELETE CASCADE,
    QuestionnaireId   UNIQUEIDENTIFIER NULL CONSTRAINT FK_Screening_Questionnaire REFERENCES candidates.Questionnaire (QuestionnaireId),
    ScreeningDate     DATE             NOT NULL,
    RoleType          NVARCHAR(100)    NOT NULL,
    CallNotes         NVARCHAR(MAX)    NOT NULL,
    Outcome           NVARCHAR(10)     NOT NULL CONSTRAINT CK_Screening_Outcome CHECK (Outcome IN (N'Pass', N'Hold', N'Fail')),
    RecordedBy        NVARCHAR(150)    NULL,
    CreatedAt         DATETIME2(3)     NOT NULL CONSTRAINT DF_Screening_CreatedAt DEFAULT (SYSUTCDATETIME())
);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_Screening_Candidate' AND object_id = OBJECT_ID(N'candidates.Screening'))
    CREATE INDEX IX_Screening_Candidate ON candidates.Screening (CandidateId, ScreeningDate) INCLUDE (Outcome);
GO

IF OBJECT_ID(N'candidates.ScreeningAnswer', N'U') IS NULL
CREATE TABLE candidates.ScreeningAnswer (
    ScreeningAnswerId UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_ScreeningAnswer_Id DEFAULT (NEWSEQUENTIALID()) CONSTRAINT PK_ScreeningAnswer PRIMARY KEY,
    ScreeningId       UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_ScreeningAnswer_Screening REFERENCES candidates.Screening (ScreeningId) ON DELETE CASCADE,
    Sequence          SMALLINT         NOT NULL,
    QuestionText      NVARCHAR(500)    NOT NULL,
    AnswerText        NVARCHAR(MAX)    NULL,
    CONSTRAINT UQ_ScreeningAnswer_Seq UNIQUE (ScreeningId, Sequence)
);
GO

IF OBJECT_ID(N'candidates.ScreeningSkillRating', N'U') IS NULL
CREATE TABLE candidates.ScreeningSkillRating (
    ScreeningSkillRatingId UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_ScreeningSkillRating_Id DEFAULT (NEWSEQUENTIALID()) CONSTRAINT PK_ScreeningSkillRating PRIMARY KEY,
    ScreeningId            UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_ScreeningSkillRating_Screening REFERENCES candidates.Screening (ScreeningId) ON DELETE CASCADE,
    SkillName              NVARCHAR(100)    NOT NULL,
    Weight                 TINYINT          NOT NULL CONSTRAINT CK_ScreeningSkillRating_Weight CHECK (Weight BETWEEN 1 AND 3),
    Rating                 TINYINT          NOT NULL CONSTRAINT CK_ScreeningSkillRating_Rating CHECK (Rating BETWEEN 0 AND 5),
    CONSTRAINT UQ_ScreeningSkillRating UNIQUE (ScreeningId, SkillName)
);
GO

IF OBJECT_ID(N'candidates.CandidateReference', N'U') IS NULL
CREATE TABLE candidates.CandidateReference (
    ReferenceId       UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_CandidateReference_Id DEFAULT (NEWSEQUENTIALID()) CONSTRAINT PK_CandidateReference PRIMARY KEY,
    CandidateId       UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_CandidateReference_Candidate REFERENCES candidates.Candidate (CandidateId) ON DELETE CASCADE,
    RefereeName       NVARCHAR(150)    NOT NULL,
    Organisation      NVARCHAR(150)    NULL,
    Relationship      NVARCHAR(100)    NULL,
    Email             NVARCHAR(254)    NULL,
    Phone             NVARCHAR(30)     NULL,
    RequestedDate     DATE             NULL,
    ReferenceStatus   NVARCHAR(12)     NOT NULL CONSTRAINT DF_CandidateReference_Status DEFAULT (N'Requested')
                                       CONSTRAINT CK_CandidateReference_Status CHECK (ReferenceStatus IN (N'Requested', N'Received', N'Declined', N'Unreachable')),
    ResponseText      NVARCHAR(MAX)    NULL,
    CONSTRAINT CK_CandidateReference_Response CHECK (ReferenceStatus <> N'Received' OR ResponseText IS NOT NULL)
);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_CandidateReference_Candidate' AND object_id = OBJECT_ID(N'candidates.CandidateReference'))
    CREATE INDEX IX_CandidateReference_Candidate ON candidates.CandidateReference (CandidateId) INCLUDE (ReferenceStatus);
GO

-- Police and Working With Vulnerable People checks, one row per candidate per check type.
IF OBJECT_ID(N'candidates.BackgroundCheck', N'U') IS NULL
CREATE TABLE candidates.BackgroundCheck (
    CandidateId        UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_BackgroundCheck_Candidate REFERENCES candidates.Candidate (CandidateId) ON DELETE CASCADE,
    CheckType          NVARCHAR(10)     NOT NULL CONSTRAINT CK_BackgroundCheck_Type CHECK (CheckType IN (N'Police', N'WWVP')),
    IsApplicable       BIT              NOT NULL CONSTRAINT DF_BackgroundCheck_IsApplicable DEFAULT (1),
    CheckStatus        NVARCHAR(15)     NOT NULL CONSTRAINT DF_BackgroundCheck_Status DEFAULT (N'Not started')
                                        CONSTRAINT CK_BackgroundCheck_Status CHECK (CheckStatus IN (N'Not started', N'Requested', N'Cleared', N'Adverse', N'Not applicable')),
    CheckDate          DATE             NULL,
    ExpiryDate         DATE             NULL,
    RegistrationNumber NVARCHAR(50)     NULL,
    CONSTRAINT PK_BackgroundCheck PRIMARY KEY (CandidateId, CheckType)
);
GO

/* ======================= Onboarding (req 3.1.3) ======================= */

IF OBJECT_ID(N'candidates.CandidateDocument', N'U') IS NULL
CREATE TABLE candidates.CandidateDocument (
    DocumentId        UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_CandidateDocument_Id DEFAULT (NEWSEQUENTIALID()) CONSTRAINT PK_CandidateDocument PRIMARY KEY,
    CandidateId       UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_CandidateDocument_Candidate REFERENCES candidates.Candidate (CandidateId) ON DELETE CASCADE,
    DocumentTypeCode  NVARCHAR(40)     NOT NULL CONSTRAINT FK_CandidateDocument_Type REFERENCES candidates.DocumentType (DocumentTypeCode),
    Description       NVARCHAR(200)    NOT NULL,
    FileName          NVARCHAR(260)    NULL,
    FileSizeBytes     BIGINT           NULL,
    StorageUri        NVARCHAR(500)    NULL,   -- location in the central document store (Module 10.3); contents are not kept in this table
    ExpiryDate        DATE             NULL,
    UploadedAt        DATETIME2(3)     NOT NULL CONSTRAINT DF_CandidateDocument_UploadedAt DEFAULT (SYSUTCDATETIME()),
    UploadedBy        NVARCHAR(150)    NULL
);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_CandidateDocument_Candidate' AND object_id = OBJECT_ID(N'candidates.CandidateDocument'))
    CREATE INDEX IX_CandidateDocument_Candidate ON candidates.CandidateDocument (CandidateId, DocumentTypeCode) INCLUDE (ExpiryDate);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_CandidateDocument_Expiry' AND object_id = OBJECT_ID(N'candidates.CandidateDocument'))
    CREATE INDEX IX_CandidateDocument_Expiry ON candidates.CandidateDocument (ExpiryDate) WHERE ExpiryDate IS NOT NULL;
GO

IF OBJECT_ID(N'candidates.CandidateInduction', N'U') IS NULL
CREATE TABLE candidates.CandidateInduction (
    CandidateId       UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_CandidateInduction_Candidate REFERENCES candidates.Candidate (CandidateId) ON DELETE CASCADE,
    InductionTypeCode NVARCHAR(30)     NOT NULL CONSTRAINT FK_CandidateInduction_Type REFERENCES candidates.InductionType (InductionTypeCode),
    CompletedDate     DATE             NOT NULL,
    Notes             NVARCHAR(500)    NULL,
    CONSTRAINT PK_CandidateInduction PRIMARY KEY (CandidateId, InductionTypeCode)
);
GO

-- 1:1 onboarding record: superannuation details and contractor agreement tracking.
IF OBJECT_ID(N'candidates.CandidateOnboarding', N'U') IS NULL
CREATE TABLE candidates.CandidateOnboarding (
    CandidateId          UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_CandidateOnboarding PRIMARY KEY
                                          CONSTRAINT FK_CandidateOnboarding_Candidate REFERENCES candidates.Candidate (CandidateId) ON DELETE CASCADE,
    SuperFundName        NVARCHAR(150)    NULL,
    SuperMemberNumber    NVARCHAR(30)     NULL,
    SuperUsi             NVARCHAR(20)     NULL,
    AgreementStatus      NVARCHAR(20)     NOT NULL CONSTRAINT DF_CandidateOnboarding_Agreement DEFAULT (N'Not generated')
                                          CONSTRAINT CK_CandidateOnboarding_Agreement CHECK (AgreementStatus IN (N'Not generated', N'Draft', N'Sent for signature', N'Signed')),
    AgreementGeneratedOn DATE             NULL,
    AgreementSentOn      DATE             NULL,
    AgreementSignedOn    DATE             NULL,
    CONSTRAINT CK_CandidateOnboarding_Signed CHECK (AgreementStatus <> N'Signed' OR AgreementSignedOn IS NOT NULL)
);
GO

/*
  Bank details (req 3.1.3 "bank details (encrypted)"). Kept in their own table so access can be restricted separately.
  Encrypted by the application (AES-256-GCM) before it reaches the database; SQL Server stores only IV + ciphertext.
  AccountLast4 is the only plaintext, for display.
*/
IF OBJECT_ID(N'candidates.CandidateBankDetail', N'U') IS NULL
CREATE TABLE candidates.CandidateBankDetail (
    CandidateId       UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_CandidateBankDetail PRIMARY KEY
                                       CONSTRAINT FK_CandidateBankDetail_Candidate REFERENCES candidates.Candidate (CandidateId) ON DELETE CASCADE,
    EncryptionIv      VARBINARY(16)    NOT NULL,
    Ciphertext        VARBINARY(MAX)   NOT NULL,
    KeyVersion        SMALLINT         NOT NULL CONSTRAINT DF_CandidateBankDetail_KeyVersion DEFAULT (1),  -- supports key rotation
    AccountLast4      CHAR(4)          NOT NULL CONSTRAINT CK_CandidateBankDetail_Last4 CHECK (AccountLast4 NOT LIKE '%[^0-9]%'),
    UpdatedAt         DATETIME2(3)     NOT NULL CONSTRAINT DF_CandidateBankDetail_UpdatedAt DEFAULT (SYSUTCDATETIME())
);
GO

/* ======================= Audit log (req 3.10.2, NFR audit logging) ======================= */
-- No FK to Candidate: audit rows must outlive merges and erasures.
IF OBJECT_ID(N'candidates.AuditLog', N'U') IS NULL
CREATE TABLE candidates.AuditLog (
    AuditId           BIGINT           IDENTITY(1, 1) NOT NULL CONSTRAINT PK_AuditLog PRIMARY KEY,
    OccurredAt        DATETIME2(3)     NOT NULL CONSTRAINT DF_AuditLog_OccurredAt DEFAULT (SYSUTCDATETIME()),
    UserName          NVARCHAR(150)    NOT NULL,
    Action            NVARCHAR(100)    NOT NULL,
    CandidateId       UNIQUEIDENTIFIER NULL,
    Details           NVARCHAR(1000)   NULL
);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_AuditLog_Candidate' AND object_id = OBJECT_ID(N'candidates.AuditLog'))
    CREATE INDEX IX_AuditLog_Candidate ON candidates.AuditLog (CandidateId, OccurredAt) WHERE CandidateId IS NOT NULL;
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_AuditLog_OccurredAt' AND object_id = OBJECT_ID(N'candidates.AuditLog'))
    CREATE INDEX IX_AuditLog_OccurredAt ON candidates.AuditLog (OccurredAt);
GO

/* ======================= Data classification (Privacy Act PII) ======================= */
ADD SENSITIVITY CLASSIFICATION TO
    candidates.Candidate.FirstName, candidates.Candidate.LastName
    WITH (LABEL = 'Confidential - Personal', INFORMATION_TYPE = 'Name', RANK = MEDIUM);
ADD SENSITIVITY CLASSIFICATION TO
    candidates.Candidate.Email, candidates.Candidate.Phone, candidates.Candidate.Location,
    candidates.CandidateReference.Email, candidates.CandidateReference.Phone
    WITH (LABEL = 'Confidential - Personal', INFORMATION_TYPE = 'Contact Info', RANK = MEDIUM);
ADD SENSITIVITY CLASSIFICATION TO
    candidates.Candidate.VisaType, candidates.Candidate.VisaExpiry, candidates.Candidate.ClearanceLevel
    WITH (LABEL = 'Confidential - Personal', INFORMATION_TYPE = 'National ID', RANK = HIGH);
ADD SENSITIVITY CLASSIFICATION TO
    candidates.Candidate.Abn, candidates.CandidateOnboarding.SuperMemberNumber,
    candidates.CandidateBankDetail.Ciphertext, candidates.CandidateBankDetail.AccountLast4
    WITH (LABEL = 'Highly Confidential', INFORMATION_TYPE = 'Financial', RANK = HIGH);
GO
